# Generated by Django 3.2.13 on 2022-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leave_city', models.CharField(max_length=100, null=True)),
                ('arrive_city', models.CharField(max_length=100, null=True)),
                ('leave_time', models.DateTimeField(null=True)),
                ('arrive_time', models.DateTimeField(null=True)),
                ('capacity', models.IntegerField(default=0, null=True)),
                ('book_sum', models.IntegerField(default=0, null=True)),
                ('income', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
