# Generated by Django 3.2.13 on 2022-09-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0002_flight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': '机票', 'verbose_name_plural': '机票'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': '航班', 'verbose_name_plural': '航班'},
        ),
    ]
